### ISSUE TITLE
Call to undefined function yaml_parse_file()

### ISSUE THREAD

**Issue by cgiupponi** [WPBP/generator#60]
Hi, I've just installed the generator with composer but when I run it I get:

```
(>'-')> WPBP Code Generator
!! Light color scheme in use !!

😎 Downloading 3.3.0 package
Extract Boilerplate
Boilerplate Extracted
Rename/Remove in progress
Generation done, I am superfast! You: (ʘ_ʘ)

sh: 1: git: not found
😎 .git folder generated
😎 .gitignore file generated
😀 NPM install in progress (takes a while... sadly)
😎 NPM install done
😎 NPM build done

Fatal error: Uncaught Error: Call to undefined function yaml_parse_file() in /root/.composer/vendor/wpbp/generator/generator/tools.php:39
Stack trace:
#0 /root/.composer/vendor/wpbp/generator/generator/wpbp.php(159): grumphp()
#1 /root/.composer/vendor/wpbp/generator/generator/init.php(46): execute_generator(Array)
#2 /root/.composer/vendor/wpbp/generator/bin/wpbp-generator(11): require('/root/.composer...')
#3 /root/.composer/vendor/bin/wpbp-generator(115): include('/root/.composer...')
#4 {main}
  thrown in /root/.composer/vendor/wpbp/generator/generator/tools.php on line 39
```

Php:
```
PHP 7.4.33 (cli) (built: Nov  3 2022 16:46:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

**Comment by Mte90** [comment]
You are missing the yaml package for php as mentioned in the readme.
